name: 'Questing/Content Issues'
description: 'Issues related to quests or modpack specific content (broken quest images/typos/wrong descriptions/structure issues ect)'
labels:
  - 'Quest'
body:
  - type: 'markdown'
    attributes:
      value: |
          ## Please Read the following
  
          - If you are having issues with a specific mod, we recommend
          reporting the issue directly to the mod author
  
          - Only 1 issue per bug report, if you need to report multiple
          issues, open multiple bug reports
          
          ## Common solutions
  
          - Updating the pack to the latest available version
  
          - If you have added/updated/removed any mods, either undo the changes or
          install a second unmodified copy of the modpack and test if the issue still happens"
          
  - type: 'dropdown'
    id: 'triedSolutions'
    attributes:
      label: 'Have you tried the solutions mentioned above?'
      options:
        - 'No'
        - 'Yes'
    validations:
      required: true

  - type: 'input'
    id: 'modpack-version'
    attributes:
      label: 'Modpack Version'
      description: 'Which version of the modpack are you using?'
      placeholder: '0.6'
    validations:
      required: true

  - type: 'textarea'
    id: 'quest-desc'
    attributes:
      label: 'Describe the issue'
      description: 'Please give a thorough explanation of what happened. Attach/Link relevant images/files in relation to the issue!'
    validations:
      required: true
