version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = true
endGatewayCulling = true
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
fastitemframes = true
farmersdelight = true
eternal_starlight = true
storagedelight = true
piglinproliferation = true
tf_dnv = true
hoppergadgetry = true
cataclysm = true
easyanvils = true
friendsandfoes = true
runes = true
diagonalwalls = true
aether = true
fastpaintings = true
functionalstorage = true
moonlight = true
aether_treasure_reforging = true
handcrafted = true
ftbquests = true
hearthandharvest = true
block_factorys_bosses = true
diagonalfences = true
relics = true
eternalnether = true
netherchested = true
spell_engine = true
witcher_rpg = true
cratedelight = true
deeperdarker = true
paladins = true
endrem = true
items_displayed = true
deep_aether = true
visualworkbench = true
biomeswevegone = true
arcane_abilities = true
ironchest = true
rogues = true
lootr = true
minecraft = true
animal_feeding_trough = true
enderzoology = true
displaydelight = true
fdlib = true
fdbosses = true
betterarcheology = true
fetzisdisplays = true
travelersbackpack = true
twilightforest = true
jewelry = true
bosses_of_mass_destruction = true
waystones = true
archers = true
diagonalwindows = true
enchantinginfuser = true
illagerinvasion = true
